//DEPARTMENT ACTIONS
export const CHANGE_VERIFICATION = "CHANGE_VERIFICATION";
export const GET_LIST_DEPARTMENTS = "GET_LIST_DEPARTMENTS";
export const SAVE_DEPARTMENT = "SAVE_DEPARTMENT";
export const SET_DEPARTMENT = "SET_DEPARTMENT";
export const EDIT_DEPARTMENT = "EDIT_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
//CATEGORY ACTIONS
export const GET_LIST_CATEGORIES = "GET_LIST_CATEGORIES";